export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const SET_MESSAGE = "SET_MESSAGE"
export const GET_MESSAGE = "GET_MESSAGE"
export const CLEAR_MESSAGE = "CLEAR_MESSAGE"

export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS"
export const MESSAGE_FAIL = "MESSAGE_FAIL"

export const CREATE_TUTORIAL = "CREATE_TUTORIAL"
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS"
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL"
export const DELETE_TUTORIAL = "DELETE_TUTORIAL"
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS"
export const RETRIEVE_USER_TUTORIALS = "RETRIEVE_USER_TUTORIALS"

export const CREATE_CHAT = "CREATE_CHAT"
export const RETRIEVE_CHATS = "RETRIEVE_CHATS"
export const UPDATE_CHAT = "UPDATE_CHAT"
export const DELETE_CHAT = "DELETE_CHAT"
export const DELETE_ALL_CHATS = "DELETE_ALL_CHATS"
export const RETRIEVE_USER_CHATS = "RETRIEVE_USER_CHAT"

export const RETRIEVE_USERS = "RETRIEVE_USERS"
